# Dataframes
* it's just the collection of multiple of series

In [198]:
import numpy as np
import pandas as pd

Dataframe from dictionary

In [199]:
data={
    'name':['ace','bob','carry','danny','emma'],
    'age':[20,30,20,30,20],
    'usn':['cd041','cd031','cd023','cd043','cd082']
}

In [200]:
df=pd.DataFrame(data)
df

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

dataframe from list

In [201]:
li=[
    ['john','cd032'],
    ['jack','cd031'],
    ['jerry','cd035']
    ]
cols=['name','usn']
df1=pd.DataFrame(li)          #here the headers will be from 0 to n
print(df1)
df2=pd.DataFrame(li,columns=cols)   # setting labels
df2

       0      1
0   john  cd032
1   jack  cd031
2  jerry  cd035

    name    usn
0   john  cd032
1   jack  cd031
2  jerry  cd035

indexing of columns

In [202]:
df

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

In [203]:
df[['name','age','usn']]   
#instead of indexing we should make use of column names

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

In [204]:
df['designation']=['doctor','engineer','doctor','engineer','driver']

In [205]:
df

    name  age    usn designation
0    ace   20  cd041      doctor
1    bob   30  cd031    engineer
2  carry   20  cd023      doctor
3  danny   30  cd043    engineer
4   emma   20  cd082      driver

In [206]:
df.drop('designation',axis=1)       
#should give the axis compulsary to delete  (0 for row 1 for col)
#here the deletion doen't remove original data from dataframe permanently

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

In [207]:
df.drop(0,axis=0)

    name  age    usn designation
1    bob   30  cd031    engineer
2  carry   20  cd023      doctor
3  danny   30  cd043    engineer
4   emma   20  cd082      driver

In [208]:
df.drop('designation',axis=1,inplace=True)

In [209]:
df

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

# selecting rows

In [210]:
df.loc[[0,1]]

  name  age    usn
0  ace   20  cd041
1  bob   30  cd031

In [211]:
df.iloc[1]

name      bob
age        30
usn     cd031
Name: 1, dtype: object

In [212]:
df.iloc[[2,3,4]][['name','age']]   #for selecting subsets of rows and columns

    name  age
2  carry   20
3  danny   30
4   emma   20

conditional selection

In [213]:
df

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

In [214]:
df[df['age']>20]

    name  age    usn
1    bob   30  cd031
3  danny   30  cd043

In [215]:
df[([df['age']>20]) and (df['usn']=='cd031')]

  name  age    usn
1  bob   30  cd031

In [216]:
df [ (df['age']>20) | (df['usn'] == 'cd031')]

    name  age    usn
1    bob   30  cd031
3  danny   30  cd043

# iterating over rows and columns
* iteritemms()
* iterrows()
* itertuples()

In [217]:
df

    name  age    usn
0    ace   20  cd041
1    bob   30  cd031
2  carry   20  cd023
3  danny   30  cd043
4   emma   20  cd082

In [218]:
for i,j in df.iterrows():
    print(i,j)
    print()

0 name      ace
age        20
usn     cd041
Name: 0, dtype: object

1 name      bob
age        30
usn     cd031
Name: 1, dtype: object

2 name    carry
age        20
usn     cd023
Name: 2, dtype: object

3 name    danny
age        30
usn     cd043
Name: 3, dtype: object

4 name     emma
age        20
usn     cd082
Name: 4, dtype: object

In [219]:
clumns=list(df)

for i in clumns: 
    print(df[i])
    #print(df[i][1])
    print("-"*20)

0      ace
1      bob
2    carry
3    danny
4     emma
Name: name, dtype: str
--------------------
0    20
1    30
2    20
3    30
4    20
Name: age, dtype: int64
--------------------
0    cd041
1    cd031
2    cd023
3    cd043
4    cd082
Name: usn, dtype: str
--------------------

# Data frame methods to work with data

In [220]:
#Method returns index (row labels) of the DataFrame
df.index

RangeIndex(start=0, stop=5, step=1)

In [221]:
df.ndim

2

In [222]:
#Returns row index and column index.
df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['name', 'age', 'usn'], dtype='str')]

In [223]:
df['usn'].values

<StringArray>
['cd041', 'cd031', 'cd023', 'cd043', 'cd082']
Length: 5, dtype: str

In [224]:
#Filter using SQL-like syntax.
df.query("age > 20")

    name  age    usn
1    bob   30  cd031
3  danny   30  cd043

In [225]:
#Checks whether values belong to a list.
df[df["age"].isin([10,30])]

    name  age    usn
1    bob   30  cd031
3  danny   30  cd043

In [226]:
#to insert a new row to a dataframe
df.insert(3,"city",["mangalore","mysore","mysore","mangalore","tumkur"])
df

    name  age    usn       city
0    ace   20  cd041  mangalore
1    bob   30  cd031     mysore
2  carry   20  cd023     mysore
3  danny   30  cd043  mangalore
4   emma   20  cd082     tumkur

In [227]:
df.drop("usn",axis=1)

    name  age       city
0    ace   20  mangalore
1    bob   30     mysore
2  carry   20     mysore
3  danny   30  mangalore
4   emma   20     tumkur

In [228]:
df.drop(0,axis=0)

    name  age    usn       city
1    bob   30  cd031     mysore
2  carry   20  cd023     mysore
3  danny   30  cd043  mangalore
4   emma   20  cd082     tumkur

In [229]:
#removes the column and return it 
df.pop("age")

0    20
1    30
2    20
3    30
4    20
Name: age, dtype: int64

In [230]:
df

    name    usn       city
0    ace  cd041  mangalore
1    bob  cd031     mysore
2  carry  cd023     mysore
3  danny  cd043  mangalore
4   emma  cd082     tumkur

In [231]:
df.rename(columns={"name":"student name"})

  student name    usn       city
0          ace  cd041  mangalore
1          bob  cd031     mysore
2        carry  cd023     mysore
3        danny  cd043  mangalore
4         emma  cd082     tumkur

In [232]:
df.notnull()

   name   usn  city
0  True  True  True
1  True  True  True
2  True  True  True
3  True  True  True
4  True  True  True

In [233]:
df.sort_index()

    name    usn       city
0    ace  cd041  mangalore
1    bob  cd031     mysore
2  carry  cd023     mysore
3  danny  cd043  mangalore
4   emma  cd082     tumkur

In [234]:
df.sort_values("usn")

    name    usn       city
2  carry  cd023     mysore
1    bob  cd031     mysore
0    ace  cd041  mangalore
3  danny  cd043  mangalore
4   emma  cd082     tumkur

In [235]:
df["city"].unique()

<StringArray>
['mangalore', 'mysore', 'tumkur']
Length: 3, dtype: str

In [236]:
df["city"].nunique()

3

In [237]:
df["city"].value_counts()

city
mangalore    2
mysore       2
tumkur       1
Name: count, dtype: int64

In [238]:
df.insert(3,"age",[20,49,46,83,74])
df

    name    usn       city  age
0    ace  cd041  mangalore   20
1    bob  cd031     mysore   49
2  carry  cd023     mysore   46
3  danny  cd043  mangalore   83
4   emma  cd082     tumkur   74

In [239]:
df['age'].add(10)

0    30
1    59
2    56
3    93
4    84
Name: age, dtype: int64

In [240]:
df['age'].subtract(10)

0    10
1    39
2    36
3    73
4    64
Name: age, dtype: int64

In [241]:
df['age'].mul(10)

0    200
1    490
2    460
3    830
4    740
Name: age, dtype: int64

In [243]:
df.set_index("name")

         usn       city  age
name
ace    cd041  mangalore   20
bob    cd031     mysore   49
carry  cd023     mysore   46
danny  cd043  mangalore   83
emma   cd082     tumkur   74

In [244]:
df.reset_index()

   index   name    usn       city  age
0      0    ace  cd041  mangalore   20
1      1    bob  cd031     mysore   49
2      2  carry  cd023     mysore   46
3      3  danny  cd043  mangalore   83
4      4   emma  cd082     tumkur   74

In [246]:
new_df=df.copy()
print(new_df)

    name    usn       city  age
0    ace  cd041  mangalore   20
1    bob  cd031     mysore   49
2  carry  cd023     mysore   46
3  danny  cd043  mangalore   83
4   emma  cd082     tumkur   74

In [247]:
df['age'].rank()

0    1.0
1    3.0
2    2.0
3    5.0
4    4.0
Name: age, dtype: float64

In [248]:
df.where(df['age']>30)

    name    usn       city   age
0    NaN    NaN        NaN   NaN
1    bob  cd031     mysore  49.0
2  carry  cd023     mysore  46.0
3  danny  cd043  mangalore  83.0
4   emma  cd082     tumkur  74.0

* DataFrame basics (shape, columns, index, dtypes)
* Selecting data (loc, iloc, query, isin)
* Modifying data (insert, drop, rename)
* Missing values (isnull, fillna, dropna)
* Sorting (sort_values, sort_index)
* Unique values (unique, nunique, value_counts)
* Arithmetic (add, sub, mul, div)
* Duplicates (duplicated, drop_duplicates)
* Index operations (set_index, reset_index)
* Sampling and ranking (sample, nsmallest, nlargest, rank)
* Utility methods (copy, where)