# Dataframes
* it's just the collection of multiple of series

In [1]:
import numpy as np
import pandas as pd

Dataframe from dictionary

In [2]:
data={
    'name':['ace','bob','carry','danny','emma'],
    'age':[20,30,20,30,20],
    'usn':['cd021','cd031','cd043','cd083','cd032']
}

In [3]:
df=pd.DataFrame(data)
df

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043
3  danny   30  cd083
4   emma   20  cd032

dataframe from list

In [4]:
li=[
    ['john','cd032'],
    ['jack','cd031'],
    ['jerry','cd035']
    ]
cols=['name','usn']
df1=pd.DataFrame(li)          #here the headers will be from 0 to n
print(df1)
df2=pd.DataFrame(li,columns=cols)   # setting labels
df2

       0      1
0   john  cd032
1   jack  cd031
2  jerry  cd035

    name    usn
0   john  cd032
1   jack  cd031
2  jerry  cd035

indexing of columns

In [5]:
df

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043
3  danny   30  cd083
4   emma   20  cd032

In [6]:
df[['name','age','usn']]   
#instead of indexing we should make use of column names

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043
3  danny   30  cd083
4   emma   20  cd032

In [7]:
df['designation']=['doctor','engineer','doctor','engineer','driver']

In [8]:
df

    name  age    usn designation
0    ace   20  cd021      doctor
1    bob   30  cd031    engineer
2  carry   20  cd043      doctor
3  danny   30  cd083    engineer
4   emma   20  cd032      driver

In [9]:
df.drop('designation',axis=1)       
#should give the axis compulsary to delete  (0 for row 1 for col)
#here the deletion doen't remove original data from dataframe permanently

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043
3  danny   30  cd083
4   emma   20  cd032

In [10]:
df.drop(0,axis=0)

    name  age    usn designation
1    bob   30  cd031    engineer
2  carry   20  cd043      doctor
3  danny   30  cd083    engineer
4   emma   20  cd032      driver

In [11]:
df.drop('designation',axis=1,inplace=True)

In [12]:
df

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043
3  danny   30  cd083
4   emma   20  cd032

# selecting rows

In [13]:
df.loc[[0,1,2]]

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043

In [14]:
df.iloc[1]

name      bob
age        30
usn     cd031
Name: 1, dtype: object

In [15]:
df.iloc[[2,3,4]][['name','age']]   #for selecting subsets of rows and columns

    name  age
2  carry   20
3  danny   30
4   emma   20

conditional selection

In [16]:
df

    name  age    usn
0    ace   20  cd021
1    bob   30  cd031
2  carry   20  cd043
3  danny   30  cd083
4   emma   20  cd032

In [17]:
df[df['age']>20]

    name  age    usn
1    bob   30  cd031
3  danny   30  cd083

In [18]:
df[([df['age']>20]) and (df['usn']=='cd031')]

  name  age    usn
1  bob   30  cd031

In [19]:
df [ (df['age']>20) | (df['usn'] == 'cd031')]

    name  age    usn
1    bob   30  cd031
3  danny   30  cd083