# handling missing data

In [1]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]      #nan means a null value
}

In [24]:
df=pd.DataFrame(data)

In [25]:
df

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.isna()     #to check if the value is null

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()   #to find the sum of null values

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()      #tp find if any null values exist in each row

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.dropna()    #to drop the rows with null values

     A  B    C    D
0  1.0  5  1.0  1.0

In [35]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  5  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0