In [50]:
import pandas as pd

In [51]:
import numpy as np

In [52]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [53]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [54]:
df.shape

(5, 3)

In [55]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [56]:
df.head()

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [57]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [59]:
df['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [60]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [61]:
def square(x):
    return x**2

square(df['A'])

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [62]:
df['A'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [63]:
df['A']=df['A'].apply(square)   
# to change the original dataframe permanantly

In [64]:
df

    A   B    C
0   1  10  100
1   4  20  200
2   9  30  300
3  16  40  400
4  25  50  500