In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product':['A', 'B', 'C', 'D']*5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 
               'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 
               'East', 'West', 'North', 'South'],
    'Sales':np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 
            'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df=pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = '0' + df['Date'].dt.quarter.astype(str)

In [ ]:
data

{'Date': DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
                '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
                '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
                '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
                '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20'],
               dtype='datetime64[us]', freq='D'),
 'Product': ['A',
  'B',
  'C',
  'D',
  'A',
  'B',
  'C',
  'D',
  'A',
  'B',
  'C',
  'D',
  'A',
  'B',
  'C',
  'D',
  'A',
  'B',
  'C',
  'D'],
 'Region': ['East',
  'West',
  'North',
  'South',
  'East',
  'West',
  'North',
  'South',
  'East',
  'West',
  'North',
  'South',
  'East',
  'West',
  'North',
  'South',
  'East',
  'West',
  'North',
  'South'],
 'Sales': array([900, 297, 573, 688, 479, 684, 446, 718, 366, 273, 211, 744, 581,
        511, 475, 143, 403, 620, 229, 641]),
 'Units': array([36, 98, 26, 99, 74, 55, 68, 67, 49, 76, 48, 70, 21, 16, 46, 37, 26,
        42, 28, 52]),
 'Rep': ['John',
  'Mary',
  'Bob',
  'Alice',
  'John',
  'Mary',
  'Bob',
  'Alice',
  'John',
  'Mary',
  'Bob',
  'Alice',
  'John',
  'Mary',
  'Bob',
  'Alice',
  'John',
  'Mary',
  'Bob',
  'Alice']}

In [ ]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    900     36   John  January      01
1  2023-01-02       B   West    297     98   Mary  January      01
2  2023-01-03       C  North    573     26    Bob  January      01
3  2023-01-04       D  South    688     99  Alice  January      01
4  2023-01-05       A   East    479     74   John  January      01
5  2023-01-06       B   West    684     55   Mary  January      01
6  2023-01-07       C  North    446     68    Bob  January      01
7  2023-01-08       D  South    718     67  Alice  January      01
8  2023-01-09       A   East    366     49   John  January      01
9  2023-01-10       B   West    273     76   Mary  January      01
10 2023-01-11       C  North    211     48    Bob  January      01
11 2023-01-12       D  South    744     70  Alice  January      01
12 2023-01-13       A   East    581     21   John  January      01
13 2023-01-14       B   West    511     16   Mary  January      01
14 2023-01-15       C  North    475     46    Bob  January      01
15 2023-01-16       D  South    143     37  Alice  January      01
16 2023-01-17       A   East    403     26   John  January      01
17 2023-01-18       B   West    620     42   Mary  January      01
18 2023-01-19       C  North    229     28    Bob  January      01
19 2023-01-20       D  South    641     52  Alice  January      01

In [ ]:
cat=df.groupby('Region')['Sales'].sum()
cat

Region
East     2729
North    1934
South    2934
West     2385
Name: Sales, dtype: int64

In [ ]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    900     36   John  January      01
1 2023-01-02       B   West    297     98   Mary  January      01
2 2023-01-03       C  North    573     26    Bob  January      01
3 2023-01-04       D  South    688     99  Alice  January      01
4 2023-01-05       A   East    479     74   John  January      01

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     545.8    NaN    NaN    NaN
North      NaN    NaN  386.8    NaN
South      NaN    NaN    NaN  586.8
West       NaN  477.0    NaN    NaN

In [ ]:
pd.pivot_table(df,values='Sales',index='Product',columns='Region',aggfunc=['mean'])
#value= the value on which you eed to perform operations
#index= row value
#columns= column value

          mean
Region    East  North  South   West
Product
A        545.8    NaN    NaN    NaN
B          NaN    NaN    NaN  477.0
C          NaN  386.8    NaN    NaN
D          NaN    NaN  586.8    NaN

In [ ]:
pd.pivot_table(df,values=['Sales','Units'],columns='Region',index='Product')

         Sales                      Units
Region    East  North  South   West  East North South  West
Product
A        545.8    NaN    NaN    NaN  41.2   NaN   NaN   NaN
B          NaN    NaN    NaN  477.0   NaN   NaN   NaN  57.4
C          NaN  386.8    NaN    NaN   NaN  43.2   NaN   NaN
D          NaN    NaN  586.8    NaN   NaN   NaN  65.0   NaN

# Cross Tab

In [ ]:
pd.crosstab(df['Region'],df['Product'])   #used to count the number of values

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0